In [150]:
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,precision_score,mean_squared_error

In [151]:
data=pd.read_csv("Taxi_Platform.csv")

In [152]:
data.head()

satisfaction  Gender   Customer Type  Age   Type of Travel     Class  \
0    satisfied  Female  Loyal Customer   65  Personal Travel       Eco   
1    satisfied    Male  Loyal Customer   47  Personal Travel  Business   
2    satisfied  Female  Loyal Customer   15  Personal Travel       Eco   
3    satisfied  Female  Loyal Customer   60  Personal Travel       Eco   
4    satisfied  Female  Loyal Customer   70  Personal Travel       Eco   

   Road Distance  Seat comfort  time convenient  Food  Platform no  \
0            265             0                0     0            2   
1           2464             0                0     0            3   
2           2138             0                0     0            3   
3            623             0                0     0            3   
4            354             0                0     0            3   

   Ease of Online booking  In-Taxi service  Baggage handling  Cleanliness  \
0                       3                3                 3            3   
1                       3                4                 4            3   
2                       2                3                 4            4   
3                       1                1                 1            1   
4                       2                2                 2            2   

   Departure Delay in Minutes  Arrival Delay in Minutes  
0                           0                       0.0  
1                         310                     305.0  
2                           0                       0.0  
3                           0                       0.0  
4                           0                       0.0

In [153]:
data.shape

(129880, 17)

In [154]:
data.dropna(inplace=True)

In [155]:
data.shape

(129487, 17)

In [156]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129487 entries, 0 to 129879
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   satisfaction                129487 non-null  object 
 1   Gender                      129487 non-null  object 
 2   Customer Type               129487 non-null  object 
 3   Age                         129487 non-null  int64  
 4   Type of Travel              129487 non-null  object 
 5   Class                       129487 non-null  object 
 6   Road Distance               129487 non-null  int64  
 7   Seat comfort                129487 non-null  int64  
 8   time convenient             129487 non-null  int64  
 9   Food                        129487 non-null  int64  
 10  Platform no                 129487 non-null  int64  
 11  Ease of Online booking      129487 non-null  int64  
 12  In-Taxi service             129487 non-null  int64  
 13  Baggage handling   

In [157]:
data['satisfaction'].value_counts()

satisfaction
satisfied       70882
dissatisfied    58605
Name: count, dtype: int64

In [158]:
data['Class'] = data['Class'].map({"Business": 3, "Eco Plus": 2, "Eco": 1}) 

In [159]:
data['satisfaction'] = data['satisfaction'].map({"satisfied": 1, "dissatisfied": 0})

In [160]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [161]:
data['Gender'] = data['Gender'].map({"Female": 1, "Male": 0})

In [162]:
data['Customer Type'].value_counts()

Customer Type
Loyal Customer       105773
disloyal Customer     23714
Name: count, dtype: int64

In [163]:
data['Customer Type']=data['Customer Type'].map({"Loyal Customer": 1, "disloyal Customer": 0})

In [164]:
data['Type of Travel'].value_counts()

Type of Travel
Business travel    89445
Personal Travel    40042
Name: count, dtype: int64

In [165]:
data['Type of Travel']=data['Type of Travel'].map({"Business travel": 1, "Personal Travel": 0})

In [166]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129487 entries, 0 to 129879
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   satisfaction                129487 non-null  int64  
 1   Gender                      129487 non-null  int64  
 2   Customer Type               129487 non-null  int64  
 3   Age                         129487 non-null  int64  
 4   Type of Travel              129487 non-null  int64  
 5   Class                       129487 non-null  int64  
 6   Road Distance               129487 non-null  int64  
 7   Seat comfort                129487 non-null  int64  
 8   time convenient             129487 non-null  int64  
 9   Food                        129487 non-null  int64  
 10  Platform no                 129487 non-null  int64  
 11  Ease of Online booking      129487 non-null  int64  
 12  In-Taxi service             129487 non-null  int64  
 13  Baggage handling   

In [167]:
print(data.keys())

Index(['satisfaction', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Road Distance', 'Seat comfort', 'time convenient', 'Food',
       'Platform no', 'Ease of Online booking', 'In-Taxi service',
       'Baggage handling', 'Cleanliness', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes'],
      dtype='object')


In [168]:
x=data.drop('Road Distance',axis=1)
y=data['Road Distance']

In [169]:
x.head()

satisfaction  Gender  Customer Type  Age  Type of Travel  Class  \
0             1       1              1   65               0      1   
1             1       0              1   47               0      3   
2             1       1              1   15               0      1   
3             1       1              1   60               0      1   
4             1       1              1   70               0      1   

   Seat comfort  time convenient  Food  Platform no  Ease of Online booking  \
0             0                0     0            2                       3   
1             0                0     0            3                       3   
2             0                0     0            3                       2   
3             0                0     0            3                       1   
4             0                0     0            3                       2   

   In-Taxi service  Baggage handling  Cleanliness  Departure Delay in Minutes  \
0                3                 3            3                           0   
1                4                 4            3                         310   
2                3                 4            4                           0   
3                1                 1            1                           0   
4                2                 2            2                           0   

   Arrival Delay in Minutes  
0                       0.0  
1                     305.0  
2                       0.0  
3                       0.0  
4                       0.0

# linear regression

In [170]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4)

In [171]:
lm = LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [172]:
y_pred=lm.predict(X_test)

In [173]:
mean_squared_error(y_test,y_pred) 

901930.897020211

# kNN

In [174]:
x=data.drop('satisfaction',axis=1)
y=data['satisfaction']

In [175]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4)

In [176]:
knn=KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [177]:
y_pred=knn.predict(x_test)

In [178]:
y_pred

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [179]:
accuracy_score(y_test,y_pred)

0.6241722173955015

# logistic regression


In [180]:
log=LogisticRegression()
log.fit(x_train,y_train)

C:\Users\patel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [181]:
y_pred=log.predict(x_test)

In [182]:
y_pred

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [183]:
accuracy_score(y_test,y_pred)

0.737465006274737

# SVM

In [184]:
svm_model=svm.SVC(kernel='linear')
svm_model.fit(x_train[:100], y_train[:100])

SVC(kernel='linear')

In [185]:
y_pred=svm_model.predict(x_test[:20])

In [186]:
accuracy_score(y_test[:20],y_pred)

0.95

# decision tree


In [187]:
dtree = DecisionTreeClassifier()
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [188]:
y_pred=dtree.predict(x_test)

In [189]:
y_pred

array([0, 1, 1, ..., 0, 1, 0], dtype=int64)

In [190]:
accuracy_score(y_test,y_pred)

0.9260160247128101