In [130]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import mean_squared_error,accuracy_score,precision_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [108]:
csv=pd.read_csv("Salary_Data.csv")
# csv=csv.loc[:30]
csv

Age  Gender    Education Level              Job Title  Years    Salary
0     32.0    Male         Bachelor's      Software Engineer    5.0   90000.0
1     28.0  Female           Master's           Data Analyst    3.0   65000.0
2     45.0    Male                PhD         Senior Manager   15.0  150000.0
3     36.0  Female         Bachelor's        Sales Associate    7.0   60000.0
4     52.0    Male           Master's               Director   20.0  200000.0
...    ...     ...                ...                    ...    ...       ...
6699  49.0  Female                PhD  Director of Marketing   20.0  200000.0
6700  32.0    Male        High School        Sales Associate    3.0   50000.0
6701  30.0  Female  Bachelor's Degree      Financial Manager    4.0   55000.0
6702  46.0    Male    Master's Degree      Marketing Manager   14.0  140000.0
6703  26.0  Female        High School        Sales Executive    1.0   35000.0

[6704 rows x 6 columns]

In [109]:
newobject=LabelEncoder()
csv["Gender"]=newobject.fit_transform(csv["Gender"])
csv["Education Level"]=newobject.fit_transform(csv["Education Level"])
csv["Job Title"]=newobject.fit_transform(csv["Job Title"])
csv.dropna(inplace=True)
csv

Age  Gender  Education Level  Job Title  Years    Salary
0     32.0       1                0        177    5.0   90000.0
1     28.0       0                3         18    3.0   65000.0
2     45.0       1                5        145   15.0  150000.0
3     36.0       0                0        116    7.0   60000.0
4     52.0       1                3         26   20.0  200000.0
...    ...     ...              ...        ...    ...       ...
6699  49.0       0                5         34   20.0  200000.0
6700  32.0       1                2        116    3.0   50000.0
6701  30.0       0                1         42    4.0   55000.0
6702  46.0       1                4         97   14.0  140000.0
6703  26.0       0                2        118    1.0   35000.0

[6699 rows x 6 columns]

In [110]:
x=csv.drop(['Salary'],axis=1)
y=csv['Salary']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# Linear Regression

In [111]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [112]:
pred_y=reg.predict(x_test)
pred_y

array([152260.08847719,  69800.39596087,  73642.45444403, ...,
       186842.60828118, 106755.77922982,  82442.06667496])

In [113]:
mean_squared_error(y_test,pred_y)

973012574.5772874

# Logistic Regression

In [114]:
log=LogisticRegression()
log.fit(x_train,y_train)

C:\Users\patel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [115]:
pred_y=log.predict(x_test)
pred_y

array([185000.,  55000.,  80000., ..., 180000., 120000.,  80000.])

In [116]:
mean_squared_error(y_test,pred_y)

1113714831.1791046

In [117]:
accuracy_score(y_test,pred_y)

0.10597014925373134

In [118]:
precision_score(y_test,pred_y,average=None)

C:\Users\patel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.11392405,
       0.        , 0.        , 0.        , 0.11267606, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04938272, 0.13114754,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.09589041, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

# KNN - K Nearest Neighbors

In [119]:
knn=KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [120]:
pred_y=knn.predict(x_test)
pred_y

array([140010.,  30000.,  60000., ..., 210000., 130000., 130000.])

In [121]:
mean_squared_error(y_test,pred_y)

107870592.26044776

In [122]:
accuracy_score(y_test,pred_y)

0.7567164179104477

In [123]:
precision_score(y_test,pred_y,average=None)

C:\Users\patel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([0.        , 0.        , 0.7804878 , 1.        , 1.        ,
       0.58823529, 0.        , 1.        , 1.        , 0.89655172,
       0.        , 0.75      , 0.5       , 0.91666667, 1.        ,
       1.        , 1.        , 0.71428571, 0.        , 1.        ,
       1.        , 0.78947368, 0.33333333, 0.        , 1.        ,
       0.        , 1.        , 0.        , 0.94642857, 0.5       ,
       0.44444444, 0.        , 0.80769231, 1.        , 0.        ,
       0.        , 0.6969697 , 1.        , 0.        , 0.        ,
       0.        , 0.75675676, 0.        , 1.        , 0.        ,
       1.        , 0.        , 0.5       , 0.        , 0.76923077,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.81081081, 0.        , 0.        , 0.        , 0.77777778,
       0.        , 0.        , 0.65957447, 0.        , 0.        ,
       0.        , 0.85714286, 1.        , 0.25      , 0.85714286,
       0.        , 1.        , 1.        , 0.        , 0.67441

# SVM - Simple Vector Machine

In [124]:
svm=SVC()

In [125]:
svm.fit(x_train,y_train)

SVC()

In [126]:
pred_y=svm.predict(x_test)
pred_y

array([160000.,  55000.,  55000., ..., 140000., 120000., 100000.])

In [127]:
mean_squared_error(y_test,pred_y)

1430924592.3731344

In [128]:
accuracy_score(y_test,pred_y)

0.12164179104477611

In [129]:
precision_score(y_test,pred_y,average=None)

C:\Users\patel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14071856,
       0.        , 0.        , 0.        , 0.12837838, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07843137, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

# Decision Tree

In [132]:
tree=DecisionTreeClassifier()
tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [134]:
pred_y=tree.predict(x_test)
pred_y

array([140010.,  30000.,  60000., ..., 210000., 130000., 130000.])

In [135]:
mean_squared_error(y_test,pred_y)

130690804.09701492

In [136]:
accuracy_score(y_test,pred_y)

0.7813432835820896

In [138]:
 from sklearn.tree import export_graphviz
# import graphviz
# dot_data = export_graphviz(tree, out_file=None, feature_names=x_train.columns, class_names=['class1', 'class2', ...])
# graph = graphviz.Source(dot_data)
# graph.render("decision_tree")


C:\Users\patel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([0.        , 0.        , 0.7804878 , 1.        , 1.        ,
       0.81818182, 0.6       , 1.        , 1.        , 0.92857143,
       0.25      , 0.        , 1.        , 0.84615385, 1.        ,
       0.66666667, 1.        , 0.85714286, 1.        , 1.        ,
       0.85714286, 0.        , 0.        , 1.        , 1.        ,
       0.        , 0.94736842, 1.        , 0.        , 0.44444444,
       0.        , 0.88235294, 0.5       , 1.        , 0.76666667,
       1.        , 0.        , 0.        , 0.81578947, 1.        ,
       1.        , 0.        , 1.        , 0.        , 1.        ,
       0.        , 0.875     , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.71794872, 0.        ,
       0.        , 0.8125    , 0.        , 1.        , 0.75      ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       1.        , 0.25      , 0.77419355, 0.        , 1.        ,
       1.        , 0.        , 0.7       , 0.        , 0.     

In [139]:
 from sklearn.tree import export_graphviz
import graphviz
dot_data = export_graphviz(tree, out_file=None, feature_names=x_train.columns, class_names=['class1', 'class2', ...])
graph = graphviz.Source(dot_data)
graph.render("decision_tree")


ModuleNotFoundError: No module named 'graphviz'